### PR TITLE
Avoid custom registration for the Json serializer

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Simplify the use of the JsonSerializer with the core distributed cache.

And enable the [NHibernate documentation example](https://nhibernate.info/doc/nhibernate-reference/caches.html#NHibernate.Caches.CoreDistributedCache) to actually work.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
The async regen action is [denied the right to push](https://github.com/nhibernate/NHibernate-Caches/actions/runs/3307908238/jobs/5459899312#step:5:19). I am manually re generating the async code.

**Comment by hazzik** [comment]
Bot did not have access to the repo

**Comment by hazzik** [comment]
Ooops:)

**Review by hazzik — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Thanks.

**Pull request merged**
